version: '2'
services:
    api:
        build: ./api
        volumes:
            - ./api/src:/src
        ports:
            - "8000:8000"
        links:
            - mongodb
            - cloudinary
    web:
        build: ./web
        volumes:
            - ./web/src:/src
        ports:
            - "8080:8080"
    cloudinary:
        image: cloudinary-mock
        ports:
            - "9080:9080"
            - "9443:9443"
    mongodb:
        image: mongo:3.0
        ports:
            - "27017:27017"
