version: '2'
services:
    web:
        build: .
        container_name: nodejs-ad-web
        volumes:
            - .:/home/nodemon/code
        ports:
            - "8000:8000"
        links:
            - mongodb
    mongodb:
        image: mongo:3.0
        container_name: mongodb
        ports:
            - "27017:27017"